name: gpg
channels:
  - conda-forge
dependencies:
  - make
  - cmake>=3.27
  - ninja
  - python=3.13
  - eigen=3.4.0
  - pybind11>=3.0.2
  - scikit-build-core>=0.11
  - pip
  - pip:
    - numpy>=2.0
    - pandas>=2.2
    - scikit-learn>=1.7,<2.0
    - sympy>=1.13
    - sympytorch>=0.1.4
    - torch>=2.11
